os: linux
dist: focal
language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
install:
  - pip install --upgrade pip
  - pip install --upgrade pyyaml requests websockets
script:
  - pip freeze
  - python setup.py test
