name: ruff Lint

on: [push, pull_request]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: ruff Lint
        uses: astral-sh/ruff-action@v4
